[package]
name = "latex"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
walkdir = "2.5.0"
tempfile = "3"
